function seven(a, b, c, d, e, f, g) {
  var xhr = new XMLHttpRequest();
  xhr.open("GET",
    "http://localhost:3000/proxy2?=", false);
  xhr.send();
  var obj = JSON.parse(xhr.responseText);

  console.log(obj);

  $("#title1").html(obj.GetParkInfo.row[a].PARKING_NAME);
  $("#text1").html(`주소 : ${obj.GetParkInfo.row[a].ADDR}<br>전화번호 : ${obj.GetParkInfo.row[a].TEL}<br>주차장 종류 : ${obj.GetParkInfo.row[a].PARKING_TYPE_NM}<br>유/무료 : ${obj.GetParkInfo.row[a].PAY_NY}<br>기본 주차 요금 : ${obj.GetParkInfo.row[a].RATES}<br>기본 주차 시간 : ${obj.GetParkInfo.row[a].TIME_RATE}<br>추가 단위 요금 : ${obj.GetParkInfo.row[a].ADD_RATES}<br>추가 단위 시간 : ${obj.GetParkInfo.row[a].ADD_TIME_RATE}<br>일 최대 요금 : ${obj.GetParkInfo.row[a].DAY_MAXIMUM}<br>평일 OPEN : ${obj.GetParkInfo.row[a].WEEKDAY_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[a].WEEKDAY_END_TIME}<br>평일 OPEN : ${obj.GetParkInfo.row[a].WEEKEND_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[a].WEEKEND_END_TIME}<br>야간 무료개방 : ${obj.GetParkInfo.row[a].NIGHT_FREE_OPEN_NM}<br>`)
  $("#title2").html(obj.GetParkInfo.row[b].PARKING_NAME);
  $("#text2").html(`주소 : ${obj.GetParkInfo.row[b].ADDR}<br>전화번호 : ${obj.GetParkInfo.row[b].TEL}<br>주차장 종류 : ${obj.GetParkInfo.row[b].PARKING_TYPE_NM}<br>유/무료 : ${obj.GetParkInfo.row[b].PAY_NY}<br>기본 주차 요금 : ${obj.GetParkInfo.row[b].RATES}<br>기본 주차 시간 : ${obj.GetParkInfo.row[b].TIME_RATE}<br>추가 단위 요금 : ${obj.GetParkInfo.row[b].ADD_RATES}<br>추가 단위 시간 : ${obj.GetParkInfo.row[b].ADD_TIME_RATE}<br>일 최대 요금 : ${obj.GetParkInfo.row[b].DAY_MAXIMUM}<br>평일 OPEN : ${obj.GetParkInfo.row[b].WEEKDAY_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[b].WEEKDAY_END_TIME}<br>평일 OPEN : ${obj.GetParkInfo.row[b].WEEKEND_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[b].WEEKEND_END_TIME}<br>야간 무료개방 : ${obj.GetParkInfo.row[b].NIGHT_FREE_OPEN_NM}<br>`)
  $("#title3").html(obj.GetParkInfo.row[c].PARKING_NAME);
  $("#text3").html(`주소 : ${obj.GetParkInfo.row[c].ADDR}<br>전화번호 : ${obj.GetParkInfo.row[c].TEL}<br>주차장 종류 : ${obj.GetParkInfo.row[c].PARKING_TYPE_NM}<br>유/무료 : ${obj.GetParkInfo.row[c].PAY_NY}<br>기본 주차 요금 : ${obj.GetParkInfo.row[c].RATES}<br>기본 주차 시간 : ${obj.GetParkInfo.row[c].TIME_RATE}<br>추가 단위 요금 : ${obj.GetParkInfo.row[c].ADD_RATES}<br>추가 단위 시간 : ${obj.GetParkInfo.row[c].ADD_TIME_RATE}<br>일 최대 요금 : ${obj.GetParkInfo.row[c].DAY_MAXIMUM}<br>평일 OPEN : ${obj.GetParkInfo.row[c].WEEKDAY_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[c].WEEKDAY_END_TIME}<br>평일 OPEN : ${obj.GetParkInfo.row[c].WEEKEND_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[c].WEEKEND_END_TIME}<br>야간 무료개방 : ${obj.GetParkInfo.row[c].NIGHT_FREE_OPEN_NM}<br>`)
  $("#title4").html(obj.GetParkInfo.row[d].PARKING_NAME);
  $("#text4").html(`주소 : ${obj.GetParkInfo.row[d].ADDR}<br>전화번호 : ${obj.GetParkInfo.row[d].TEL}<br>주차장 종류 : ${obj.GetParkInfo.row[d].PARKING_TYPE_NM}<br>유/무료 : ${obj.GetParkInfo.row[d].PAY_NY}<br>기본 주차 요금 : ${obj.GetParkInfo.row[d].RATES}<br>기본 주차 시간 : ${obj.GetParkInfo.row[d].TIME_RATE}<br>추가 단위 요금 : ${obj.GetParkInfo.row[d].ADD_RATES}<br>추가 단위 시간 : ${obj.GetParkInfo.row[d].ADD_TIME_RATE}<br>일 최대 요금 : ${obj.GetParkInfo.row[d].DAY_MAXIMUM}<br>평일 OPEN : ${obj.GetParkInfo.row[d].WEEKDAY_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[d].WEEKDAY_END_TIME}<br>평일 OPEN : ${obj.GetParkInfo.row[d].WEEKEND_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[d].WEEKEND_END_TIME}<br>야간 무료개방 : ${obj.GetParkInfo.row[d].NIGHT_FREE_OPEN_NM}<br>`)
  $("#title5").html(obj.GetParkInfo.row[e].PARKING_NAME);
  $("#text5").html(`주소 : ${obj.GetParkInfo.row[e].ADDR}<br>전화번호 : ${obj.GetParkInfo.row[e].TEL}<br>주차장 종류 : ${obj.GetParkInfo.row[e].PARKING_TYPE_NM}<br>유/무료 : ${obj.GetParkInfo.row[e].PAY_NY}<br>기본 주차 요금 : ${obj.GetParkInfo.row[e].RATES}<br>기본 주차 시간 : ${obj.GetParkInfo.row[e].TIME_RATE}<br>추가 단위 요금 : ${obj.GetParkInfo.row[e].ADD_RATES}<br>추가 단위 시간 : ${obj.GetParkInfo.row[e].ADD_TIME_RATE}<br>일 최대 요금 : ${obj.GetParkInfo.row[e].DAY_MAXIMUM}<br>평일 OPEN : ${obj.GetParkInfo.row[e].WEEKDAY_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[e].WEEKDAY_END_TIME}<br>평일 OPEN : ${obj.GetParkInfo.row[e].WEEKEND_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[e].WEEKEND_END_TIME}<br>야간 무료개방 : ${obj.GetParkInfo.row[e].NIGHT_FREE_OPEN_NM}<br>`)
  $("#title6").html(obj.GetParkInfo.row[f].PARKING_NAME);
  $("#text6").html(`주소 : ${obj.GetParkInfo.row[f].ADDR}<br>전화번호 : ${obj.GetParkInfo.row[f].TEL}<br>주차장 종류 : ${obj.GetParkInfo.row[f].PARKING_TYPE_NM}<br>유/무료 : ${obj.GetParkInfo.row[f].PAY_NY}<br>기본 주차 요금 : ${obj.GetParkInfo.row[f].RATES}<br>기본 주차 시간 : ${obj.GetParkInfo.row[f].TIME_RATE}<br>추가 단위 요금 : ${obj.GetParkInfo.row[f].ADD_RATES}<br>추가 단위 시간 : ${obj.GetParkInfo.row[f].ADD_TIME_RATE}<br>일 최대 요금 : ${obj.GetParkInfo.row[f].DAY_MAXIMUM}<br>평일 OPEN : ${obj.GetParkInfo.row[f].WEEKDAY_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[f].WEEKDAY_END_TIME}<br>평일 OPEN : ${obj.GetParkInfo.row[f].WEEKEND_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[f].WEEKEND_END_TIME}<br>야간 무료개방 : ${obj.GetParkInfo.row[f].NIGHT_FREE_OPEN_NM}<br>`)
  $("#title7").html(obj.GetParkInfo.row[g].PARKING_NAME);
  $("#text7").html(`주소 : ${obj.GetParkInfo.row[g].ADDR}<br>전화번호 : ${obj.GetParkInfo.row[g].TEL}<br>주차장 종류 : ${obj.GetParkInfo.row[g].PARKING_TYPE_NM}<br>유/무료 : ${obj.GetParkInfo.row[g].PAY_NY}<br>기본 주차 요금 : ${obj.GetParkInfo.row[g].RATES}<br>기본 주차 시간 : ${obj.GetParkInfo.row[g].TIME_RATE}<br>추가 단위 요금 : ${obj.GetParkInfo.row[g].ADD_RATES}<br>추가 단위 시간 : ${obj.GetParkInfo.row[g].ADD_TIME_RATE}<br>일 최대 요금 : ${obj.GetParkInfo.row[g].DAY_MAXIMUM}<br>평일 OPEN : ${obj.GetParkInfo.row[g].WEEKDAY_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[g].WEEKDAY_END_TIME}<br>평일 OPEN : ${obj.GetParkInfo.row[g].WEEKEND_BEGIN_TIME}<br>평일 CLOSE : ${obj.GetParkInfo.row[e].WEEKEND_END_TIME}<br>야간 무료개방 : ${obj.GetParkInfo.row[g].NIGHT_FREE_OPEN_NM}<br>`)
};


seven(0,1,2,3,4,5,6);
